Repository ISIS3510-202410-Team5/Android-Kotlin, pull requests merged in 2024-04, with the labels that each got.

#57 feat: added new fields in product data class
  app/src/main/java/com/example/unimarket/model/Product.kt
Labels: enhancement, Sprint 3

#58 Branch juan
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/unimarket/MainActivity.kt
  app/src/main/java/com/example/unimarket/di/AppModule.kt
  app/src/main/java/com/example/unimarket/model/Usuario.kt
  app/src/main/java/com/example/unimarket/repositories/UsuariosRepository.kt
  app/src/main/java/com/example/unimarket/ui/Login/model/FirestoreProvider.kt
  app/src/main/java/com/example/unimarket/ui/Login/model/LoginModel.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/LoginScreen.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/LoginViewModel.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/SignUpScreen.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/SignUpViewModel.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/UserInfoScreen.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/UserInfoViewModel.kt
  app/src/main/java/com/example/unimarket/ui/camera/ui/CameraScreen.kt
  app/src/main/java/com/example/unimarket/ui/camera/ui/CameraViewModel.kt
  app/src/main/java/com/example/unimarket/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/unimarket/ui/usuario/UsuarioPerfilScreen.kt
  app/src/main/java/com/example/unimarket/ui/usuario/UsuarioViewModel.kt
  app/src/main/res/drawable/fotousuario.jpg
Labels: enhancement, Sprint 3

#61 60 shared preference object and api to access preferences and adit values
  app/src/main/java/com/example/unimarket/di/SharedPreferenceService.kt
  app/src/main/java/com/example/unimarket/model/Usuario.kt
  app/src/main/java/com/example/unimarket/repositories/UsuariosRepository.kt
  app/src/main/java/com/example/unimarket/sensor/ShakeDetector.kt
  app/src/main/java/com/example/unimarket/ui/FirebaseApplication.kt
  app/src/main/java/com/example/unimarket/ui/navigation/NavGraph.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 3

#63 Correct the location functionality
  app/src/main/java/com/example/unimarket/data/DefaultLocationTracker.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/ListProducts.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/LocationViewModel.kt
Labels: Sprint 3

#64 Create cache structure
  app/src/main/java/com/example/unimarket/model/ProductCache.kt
Labels: Sprint 3

#65 Create connection repository
  app/src/main/java/com/example/unimarket/repositories/ConnectivityRepository.kt
Labels: Sprint 3

#66 Create conecction verification
  app/src/main/java/com/example/unimarket/ui/ListProducts/ProductListViewModel.kt
Labels: Sprint 3

#67 creation of the product detail view
  app/src/main/java/com/example/unimarket/ui/DetailProduct/ProductDetail.kt
Labels: Sprint 3

#68 Creation of the viewmodel of detail product view
  app/src/main/java/com/example/unimarket/ui/DetailProduct/DetailProductViewModel.kt
Labels: Sprint 3

#70 62 add roomdatabase in order to persist cart content
  app/build.gradle.kts
  app/src/main/java/com/example/unimarket/MainActivity.kt
  app/src/main/java/com/example/unimarket/db/ShoppingCartDb.kt
  app/src/main/java/com/example/unimarket/di/AppModule.kt
  app/src/main/java/com/example/unimarket/di/SharedPreferenceService.kt
  app/src/main/java/com/example/unimarket/entities/ProductoDAO.kt
  app/src/main/java/com/example/unimarket/entities/ProductoEntity.kt
  app/src/main/java/com/example/unimarket/model/Product.kt
  app/src/main/java/com/example/unimarket/model/Purchase.kt
  app/src/main/java/com/example/unimarket/model/ShoppingCart.kt
  app/src/main/java/com/example/unimarket/sensor/ShakeDetector.kt
  app/src/main/java/com/example/unimarket/ui/FirebaseApplication.kt
  app/src/main/java/com/example/unimarket/ui/home/Home.kt
  app/src/main/java/com/example/unimarket/ui/shoppingcart/ShoppingCart.kt
  app/src/main/java/com/example/unimarket/ui/shoppingcart/ShoppingCartViewModel.kt
Labels: enhancement, Sprint 3

#71 Implementation of location in product search view
  app/src/main/java/com/example/unimarket/ui/ListProducts/ListProducts.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/SelectedProductViewModel.kt
  app/src/main/java/com/example/unimarket/ui/SearchProduct/LocationViewModel.kt
  app/src/main/java/com/example/unimarket/ui/SearchProduct/SearchProduct.kt
  app/src/main/res/drawable/ic_search.png
Labels: Sprint 3

#73 Creation of the corroutine to obtain the location
  app/src/main/java/com/example/unimarket/ui/SearchProduct/LocationViewModel.kt
Labels: Sprint 3

#75 Creation of the coroutine to obtain the cache in detail
  app/src/main/java/com/example/unimarket/ui/DetailProduct/DetailProductViewModel.kt
Labels: Sprint 3

#76 creation of the corrutine that allows to search the product inside th…
  app/src/main/java/com/example/unimarket/ui/DetailProduct/DetailProductViewModel.kt
Labels: Sprint 3

#77 Navigation configuration to add the two new search and detail views
  app/build.gradle.kts
  app/src/main/java/com/example/unimarket/ui/DetailProduct/ProductDetail.kt
  app/src/main/java/com/example/unimarket/ui/navigation/NavGraph.kt
Labels: Sprint 3

#78 Adding the image cache to the product list with Glide
  app/src/main/java/com/example/unimarket/ui/DetailProduct/ProductDetail.kt
  app/src/main/res/drawable/error.png
  app/src/main/res/drawable/placeholder.png
Labels: Sprint 3

#81 Add related items
  app/src/main/java/com/example/unimarket/repositories/ProductoRepository.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/ListProducts.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/ProductListViewModel.kt
Labels: Sprint 3

#83 Created a function that consumes the productRepositorie from DetailPr…
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/unimarket/ui/DetailProduct/DetailProductViewModel.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/ProductListViewModel.kt
Labels: Sprint 3

#85 Changes on the text field of the PasswordSpace of LoginScreen and Sig…
  app/src/main/java/com/example/unimarket/ui/Login/ui/LoginScreen.kt
  app/src/main/java/com/example/unimarket/ui/Login/ui/SignUpScreen.kt
Labels: Sprint 3

#87 Fixed the NavGraph.kt issue with the info screen that crashed after s…
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/unimarket/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/unimarket/ui/usuario/UsuarioPerfilScreen.kt
Labels: bug, Sprint 3

#88 Branch samuel
  app/src/main/java/com/example/unimarket/ui/ListProducts/ListProducts.kt
  app/src/main/java/com/example/unimarket/ui/ListProducts/ProductListViewModel.kt
  app/src/main/java/com/example/unimarket/ui/SearchProduct/SearchProduct.kt
  app/src/main/java/com/example/unimarket/ui/home/Home.kt
  app/src/main/java/com/example/unimarket/ui/home/HomeViewModel.kt
Labels: Sprint 3

#90 69 protect views, home and cart
  app/src/main/java/com/example/unimarket/connection/ConnectivityObserver.kt
  app/src/main/java/com/example/unimarket/connection/NetworkConnectivityObserver.kt
  app/src/main/java/com/example/unimarket/repositories/ConnectivityRepository.kt
  app/src/main/java/com/example/unimarket/ui/FirebaseApplication.kt
  app/src/main/java/com/example/unimarket/ui/home/Home.kt
  app/src/main/java/com/example/unimarket/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/unimarket/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/unimarket/ui/publishitem/PublishItem.kt
  app/src/main/java/com/example/unimarket/ui/publishitem/PublishItemViewModel.kt
  app/src/main/java/com/example/unimarket/ui/shoppingcart/ShoppingCart.kt
  app/src/main/java/com/example/unimarket/ui/shoppingcart/ShoppingCartViewModel.kt
  app/src/main/java/com/example/unimarket/ui/usuario/ShakeSlider.kt
Labels: enhancement, Sprint 3
